.TH ODT2TXT "1" "Thu, 11 Jan 2007 03:07:45 -0200" "odt2txt 0.2" "User Commands"
.SH NAME
odt2txt \- a simple converter from OpenDocument Text to plain text
.SH DESCRIPTION
odt2txt converts an OpenDocument Text to raw text.
.PP
Syntax:   odt2txt [options] filename
.PP
Options:  \fB\-\-raw\fR         Print raw XML
.TP
\fB\-\-encoding\fR=\fIX\fR
Do not try to autodetect the terminal encoding, but
convert the document to encoding X unconditionally
To find out, which terminal encoding will be used in
auto mode, use \fB\-\-encoding\fR=\fIshow\fR
.TP
\fB\-\-width\fR=\fIX\fR
Wrap text lines after X characters. Default: 65.
If set to \fB\-1\fR then no lines will be broken
.HP
\fB\-\-output\fR=\fIfile\fR Write output to file, instead of STDOUT
.TP
\fB\-\-subst\fR=\fIX\fR
Select which non\-ascii characters shall be replaced
by ascii look\-a\-likes:
.TP
\fB\-\-subst\fR=\fIall\fR
Substitute all characters for which
substitutions are known
.TP
\fB\-\-subst\fR=\fIsome\fR
Substitute all characters which the
output charset does not contain
This is the default
.TP
\fB\-\-subst\fR=\fInone\fR
Substitute no characters
.TP
\fB\-\-force\fR
Do not stop if the mimetype if unknown
.TP
\fB\-\-version\fR
Show version and copyright information
.SH COPYRIGHT
Copyright \(co 2006,2007 Dennis Stosberg <dennis@stosberg.net>
Uses the kunzip library, Copyright 2005,2006 by Michael Kohn
.PP
This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License,
version 2 as published by the Free Software Foundation
.PP
Homepage: http://stosberg.net/odt2txt/
.PP
This manual page was written by Nelson A. de Oliveira <naoliv@debian.org>,
for the Debian project (but may be used by others).
