#!/bin/sh -e

#DEBHELPER#

if [ "$1" = configure ]; then
	update-alternatives --quiet --install /usr/bin/odt2txt odt2txt \
		/usr/bin/odt2txt.odt2txt 200 --slave /usr/share/man/man1/odt2txt.1.gz \
		odt2txt.1.gz /usr/share/man/man1/odt2txt.odt2txt.1.gz
fi
